# NumPy cheatsheet

## What is NumPy?
A python library consisting of multidimensional array objects and a collection of routines for processing those arrays. It is used because it provides high performance for mathematical and logical operations on arrays.

### Importing NumPy

In [2]:
import numpy as np

### Creating Arrays
- Creating an one-d array with the provided values

In [83]:
arr1 = np.array([2,4,6,8,10,12])
print(arr1)

[ 2  4  6  8 10 12]


- Creating a two-d array with the provided values

In [84]:
arr2 = np.array([(1,3,5),(2,4,6)], dtype=int)
print(arr2)

[[1 3 5]
 [2 4 6]]


- Creating a one-d array with only zeroes by providing the number of elements

In [85]:
arr3 = np.zeros(4)
print(arr3)

[0. 0. 0. 0.]


- Creating a two-d array of zeros by providing the shape of the matrix

In [86]:
arr4 = np.zeros((3,4))
print(arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


- Creating a array with all elements having same values by providing the shape of array and the element.

In [87]:
arr5 = np.full((3,4),2)
print(arr5)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


- Creating a random array by providing the shape of the array.

In [88]:
arr6 = np.random.rand(3,4)
print(arr6)

[[0.17035955 0.92550277 0.97154475 0.41133388]
 [0.55594509 0.61867174 0.81739063 0.04058512]
 [0.78236979 0.60607416 0.30118313 0.69551446]]


- Creating an array with all elements as 1 by providing the shape of the array

In [89]:
arr7 = np.ones((3,4))
print(arr7)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


- Creating an identity matrix by proding the shape of square matrix

In [90]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Mathematical operations on arrays
- Addition

In [91]:
sum = np.add(arr4, arr5)
print(sum)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


- Subtraction

In [92]:
diff = np.subtract(arr5, arr6)
print(diff)

[[1.82964045 1.07449723 1.02845525 1.58866612]
 [1.44405491 1.38132826 1.18260937 1.95941488]
 [1.21763021 1.39392584 1.69881687 1.30448554]]


- Element wise Multiplication on array elements, The element at a[i][j] is multiplied with b[i][j]

In [93]:
product = np.multiply(arr5,arr6)
print(product)

[[0.3407191  1.85100553 1.94308949 0.82266776]
 [1.11189019 1.23734347 1.63478126 0.08117024]
 [1.56473957 1.21214831 0.60236626 1.39102892]]


- Dot product carries normal matrix multiplication. The condition of number of columns of first array should be equal to number of rows of second array

In [94]:
arr8 = np.full((4,3),3)
dot = np.dot(arr5,arr8)
print(dot)

[[24 24 24]
 [24 24 24]
 [24 24 24]]


- Division - element from first array is divided by elements from second element (all happens element-wise). Both arr1 and arr2 must have same shape and element in arr2 must not be zero

In [95]:
div = np.divide(arr5,arr6)
print(div)

[[11.73987599  2.1609876   2.05857734  4.86223019]
 [ 3.59747756  3.23273214  2.44681052 49.27914471]
 [ 2.55633594  3.29992622  6.64047822  2.87556927]]


- Square root

In [96]:
sqrt = np.sqrt(arr5)
print(sqrt)

[[1.41421356 1.41421356 1.41421356 1.41421356]
 [1.41421356 1.41421356 1.41421356 1.41421356]
 [1.41421356 1.41421356 1.41421356 1.41421356]]


- Calculating Exponentiation of each element in the matrix

In [97]:
expo = np.exp(arr5)
print(expo)

[[7.3890561 7.3890561 7.3890561 7.3890561]
 [7.3890561 7.3890561 7.3890561 7.3890561]
 [7.3890561 7.3890561 7.3890561 7.3890561]]


- Calculate the Log values of each element in the matrix

In [98]:
log = np.log(expo)
print(log)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


- To deal with matrices containing value as 0, the log1p method adds 1 to each element and calculates the log.

In [99]:
log1 = np.log1p(arr5)
print(log1)

[[1.09861229 1.09861229 1.09861229 1.09861229]
 [1.09861229 1.09861229 1.09861229 1.09861229]
 [1.09861229 1.09861229 1.09861229 1.09861229]]


- To calculate the exponentiation of the result we got from log1p method we can use expm1 method which calculates the exponentiation of each element and subtract 1 from it

In [100]:
expo1 = np.expm1(log1)
print(expo1)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


### Basic NumPy operations

- Copying a two-d array

In [101]:
arr5_copy = np.copy(arr5)
print(arr5_copy)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


- Soritng the elements in the array

In [102]:
arr9 = [4,2,7,1,9,6]
sorted = np.sort(arr9)
print(sorted)

[1 2 4 6 7 9]


- Concatenating two numpy arrays. When axis is set to 1 the two arrays concatenate by columns whereas when axis is set to 0 the arras concatenated by rows

In [103]:
conc1 = np.concatenate((arr5,arr6), axis=1)
print(conc1)

[[2.         2.         2.         2.         0.17035955 0.92550277
  0.97154475 0.41133388]
 [2.         2.         2.         2.         0.55594509 0.61867174
  0.81739063 0.04058512]
 [2.         2.         2.         2.         0.78236979 0.60607416
  0.30118313 0.69551446]]


In [104]:
conc2 = np.concatenate((arr5,arr6), axis=0)
print(conc2)

[[2.         2.         2.         2.        ]
 [2.         2.         2.         2.        ]
 [2.         2.         2.         2.        ]
 [0.17035955 0.92550277 0.97154475 0.41133388]
 [0.55594509 0.61867174 0.81739063 0.04058512]
 [0.78236979 0.60607416 0.30118313 0.69551446]]


- Stacks the sequence of arrays in the specified axis

In [105]:
sta1 = np.stack([arr1,arr9],axis=0)
print(sta1)

[[ 2  4  6  8 10 12]
 [ 4  2  7  1  9  6]]


In [106]:
sta2 = np.stack([arr1,arr9],axis=1)
print(sta2)

[[ 2  4]
 [ 4  2]
 [ 6  7]
 [ 8  1]
 [10  9]
 [12  6]]


- Similar to the np.stack method when axis is set to 1

### Summarizing operations
 - Find the minimum value in the array

In [107]:
min = np.min(arr9)
print(min)

1


- Find the maximum value in the array

In [108]:
max = np.max(arr9)
print(max)

9


- Average of all elements

In [109]:
avg = np.mean(arr9)
print(avg)

4.833333333333333


- Standard deviation

In [110]:
std = np.std(arr9)
print(std)

2.793842435706702
